server {
    server_name mathai.tech www.mathai.tech;

    location = /love.html {
        alias /var/www/mathai-love/love.html;
    }

    location /love/ {
        alias /var/www/mathai-love/;
    }

    location /photos/ {
        alias /var/www/mathai-love/photos/;
    }

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }

    location /api {
        rewrite ^/api/(.*) /$1 break;
        proxy_pass http://127.0.0.1:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }

    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header X-Content-Type-Options "nosniff" always;

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/mathai.tech/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mathai.tech/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = www.mathai.tech) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    if ($host = mathai.tech) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    server_name mathai.tech www.mathai.tech;
    return 404; # managed by Certbot
}
