server {
    listen 80;
    listen [::]:80;
    server_name mathai.tech;

    root /var/www/mathai-love;
    index love.html;

    location = /love.html {
        try_files /love.html =404;
    }

    location /love/ {
        alias /var/www/mathai-love/;
    }

    location /photos/ {
        alias /var/www/mathai-love/photos/;
    }
}
